name: CI/CD — Build, (Optional) Generate Modules, Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # or 18/25 depending on your target

      - name: Install dependencies
        run: npm ci

      - name: Run linter (optional)
        run: echo "Lint step skipped (add lint if needed)"

      - name: Build Next.js
        run: npm run build

      - name: Optionally generate 3000+ modules
        if: ${{ secrets.GENERATE_MODULES == 'true' }}
        run: |
          echo "Generating modules in CI..."
          node scripts/generate_modules.js 3000 1
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add modules modules.json
          git commit -m "chore: add 3000 generated module stubs (auto-generated by CI)" || echo "no changes to commit"
          git push origin HEAD:main

      - name: Deploy to Render (trigger)
        if: ${{ secrets.RENDER_API_KEY && secrets.RENDER_SERVICE_ID }}
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Triggering deploy on Render..."
          curl -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": true}'
